version: "3.8"

services:

  database:
    # All my homies hate mysql
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordpress-network
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2048m

  wordpress:
    depends_on:
      - database
    image: wordpress:6.5.4-apache
    restart: unless-stopped
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306 # use the same name as database service
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./:/var/www/html # Exposes whole wp installation into the same folder as this repo
      - ./config/php.ini:/usr/local/etc/php/php.ini # Copies this php.ini from config into the container. It should appear inside the container as php.ini
    networks:
      - wordpress-network

volumes:
  db-data:


networks:
  wordpress-network:
    driver: bridge
