version: "3.8"

services:

  database:
    # All my homies hate mysql
    image: mariadb:10.6.4-focal
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordpress-network
    # deploy:
    #   resources:
    #     limits:
    #       memory: 2048m

  wordpress:
    depends_on:
      - database
    image: wordpress:6.5.4-apache
    restart: unless-stopped
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306 # use the same name as database service
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./:/var/www/html # Exposes whole wp installation into the same folder as this repo
      # Change some php setting for better life (if you can call this a life if you use wordpress)
      - ./config/docker-php-file-uploads.ini:/usr/local/etc/php/conf.d/docker-php-file-uploads.ini
      - ./config/docker-php-upload-max-filesize.ini:/usr/local/etc/php/conf.d/docker-php-upload-max-filesize.ini
      - ./config/docker-php-post-max-size.ini:/usr/local/etc/php/conf.d/docker-php-post-max-size.ini
      - ./config/docker-php-memory-limit.ini:/usr/local/etc/php/conf.d/docker-php-memory-limit.ini
      - ./config/docker-php-max-input-time.ini:/usr/local/etc/php/conf.d/docker-php-max-input-time.ini
      - ./config/docker-php-max-execution-time.ini:/usr/local/etc/php/conf.d/docker-php-max-execution-time.ini
    networks:
      - wordpress-network

volumes:
  db-data:


networks:
  wordpress-network:
    driver: bridge
